### ISSUE TITLE
spec: maybe use `<wpt>` to link spec sections to test suite

### ISSUE THREAD

**Issue by mikesamuel** [WICG/trusted-types#109]
https://tabatkins.github.io/bikeshed/#wpt-element says

> When writing tests, you can sometimes link to the section of the spec that you’re testing, to make it easier to review. But when you’re actually reading (or updating!) the spec, you can’t tell what sections are tested or untested, or what tests might need to be updated due to a change you’re making. The `<wpt>` element lets you easily link to your WPT testcases inline, right next to the text they’re testing, and helps make sure that the testsuite and the spec are kept in-sync.

> The `<wpt>` element is a block-level element for parsing purposes; place it after or between paragraphs/etc. The contents of the element are line-based: each line contains a single test path (the path under the WPT repo, so not including the domain or the /web-platforms-tests/wpt/) pointing to the test covering some nearby text.

and later

>  If you want to produce a test-annotated version of the output, specify the WPT Display metadata with the value "inline"; all of the `<wpt>` elements will become usefully-formatted lists of their contained tests, with links to wpt.fyi, the live test on w3c-test.org, and the source code on GitHub.

**Comment by koto** [comment]
For now bikeshed doesn't even see out test files (the [test database](https://github.com/tabatkins/bikeshed/blob/master/bikeshed/spec-data/readonly/wpt-tests.txt) was generated months ago). and [bails out if we reference them](https://github.com/tabatkins/bikeshed/issues/1416).
