### ISSUE TITLE
TrustedTypes.isHTML('test') throws exception

### ISSUE THREAD

**Issue by crypto** [WICG/trusted-types#134]
Native implementation in Chrome Version 74.0.3718.1 (Official Build) canary-dcheck (32-bit)
TrustedTypes.isHTML('test') throws exception if value is string

> Uncaught TypeError: Failed to execute 'isHTML' on 'TrustedTypePolicyFactory': parameter 1 ('checkedObject') is not an object.

polyfill returns false

**Comment by koto** [comment]
Filed as https://bugs.chromium.org/p/chromium/issues/detail?id=936433.
