### ISSUE TITLE
Calls to document.write are not passed to the policy (Chromium)

### ISSUE THREAD

**Issue by p-** [WICG/trusted-types#136]
Hi!
I noticed that calls to document.write are not passed to the default policy in the Chromium implementation.

Chromium Version: 74.0.3727.0

Using following dummy default policy:

    const logMe = (type, passthrough) => {
        console.log(type, passthrough);
        return passthrough;
    };

    window.TrustedTypes.createPolicy('default', {
        createHTML: s => logMe('HTML', s),
        createScript: s => logMe('Script', s),
        createScriptURL: s => logMe('ScriptURL', s),
        createURL: s => logMe('URL', s),
    }, true);

My Test HTML makes a call to document.write:
	`document.write("<b>Hello</b>");`

Expected log output:
	`HTML <b>Hello</b>`

Result:
- Using the Polyfill the output is as expected.

- Using Chromium 74.0.3727.0 the output is:

		Uncaught TypeError: Failed to execute 'write' on 'Document': This document can only write `TrustedHTML` objects.

At the same time when using the `innerHTML` sink it works as expected.

I'm sorry if this is a known or non-issue.
I wanted to ask here first, if confirmed I can also fill it on the chromium bug tracker.

**Comment by koto** [comment]
Thanks, I confirmed the issue - filed as https://bugs.chromium.org/p/chromium/issues/detail?id=938929

**Comment by koto** [comment]
This is fixed in Chromium v76.
