### ISSUE TITLE
Handle srcset attributes

### ISSUE THREAD

**Issue by koto** [WICG/trusted-types#139]
Defined here: https://html.spec.whatwg.org/multipage/embedded-content.html, right now for `img` and `source` elements, but there are also plans to add it to `script` (https://github.com/whatwg/html/issues/4432) - as such, this can potentially spawn into two new types. cc @otherdaniel

**Comment by mikesamuel** [comment]
One way to spec this might be to derive a spec abstraction from inputs like `[ [ trustedURL0, metadata0 ], ... ]` and a stringifier for the same to a string value that matches the syntax at [HTML5/srcset-attributes](https://html.spec.whatwg.org/multipage/images.html#srcset-attributes).

I can probably parameterize the type to make the stringifier compatible with the [`<script srcset>` proposal](https://github.com/whatwg/html/issues/4432) which would take *TrustedScriptURL*s.

1. Define a mapping from an rvalue that matches typescript type:
    ```ts
    type StructuredSrcsetInput<T extends TrustedType> = [ T, string? ][]
    ```
1. Define an IDL `interface StructuredSrcset` that mirrors that type.
1. Define an algorithm to map *StructuredSrcsetInput*s to *StructedSrcset* that takes a type
    1. Reject empty arrays
    1. Reject arrays with holes
    1. Require the URL be the right type (*TrustedURL*  vs *TrustedScriptURL*)
    1. Require the URL content not start or end with comma or HTML spaces to avoid stringifier ambiguity
    1. Stringifies the metadata and requires that it matches HTML valid floating point number with an optional letter at the end.
1. Define a *stringifier* for `StructedSrcset`
    1. Let out be an empty buffer
    1. Let isfirst = false
    1. For each element in structuredSrcset:
         1. Let url = Get(element, 0)  (TODO: Or some internal slot verbiage)
         1. Let metadata = Get(element, 1)   (TODO: Or some internal slot verbiage)
         1. If isfirst is true then
             1. Append `" , "` to empty buffer.  Note: the leading space is needed in case a URL without metadata appears in a position other than the end.
             1. Assign isfirst = false
         1. Append the URL content to out
         1. If metadata is not null then
             1. Append a space character (U+20)  to out
             1. Append metadata to out
    1. let srcsetString = ToString(out)
    1. return srcsetString
1. Spec a sink guard that chains the above together.

**Comment by koto** [comment]
So, from the author's perspective (please correct me if I misunderstood the patch):
 - there is no separate srcset type (e.g. `TrustedUrlSet`)
 - you can use strings for assignments to `*.srcset` (in that case, a default policy is called on the url parts with the appropriate URL type)
 - you can use a structured array when assigning to `*.srcset` (in that case, you produce the types yourself)

That last part is a bigger change, and should probably require speccing in HTML (to have a structured setter for `srcset` attributes, and than only require types for some fields). I'd rather we keep TT as close to the original DOM API as possible, for compatibility reasons. 

Perhaps we can avoid using an array with customized serialization directly in a sink and introduce a `TrustedUrlSet` type for `{img,source}.srcset` (and later `TrustedScriptUrlSet` for `script.srcset`) that serves the same purpose? We could:
- expose methods for parsing / unparsing a sting (`TrustedURLSet.unparse` etc).
- make `createURLSet` accept a string (and likely use parsing internally).
- have a separate create function that accepts the array, with `TrustedURL` for URLs.

There might be more elegant APIs, e.g. we could use a builder pattern, but I don't think `srscets` are used often enough that it warrants a very elaborate solution (unless HTML recognizes a need for a structured setter and then he hook into that).

**Comment by mikesamuel** [comment]
@koto

The general problem is we need a way of handling attribute values where one or more substring must be trustworthy.

## Option 1
1.  For each structured attribute kind
    1.  Define parser and unparser to bridge JS object that may contain TrustedType values <-> string
    1.  Define a copier function that copies a JS object, applying a function to any trusted parts it finds.
1.  Define a table from sink name to (parser, unparser, copier) triples
1.  Tweak enforcement algo to use the table

# Option 2

IIUC,

1.  For each structured attribute kind
    1.  Define a new trusted type
    1.  Add a createXXXXX method to policy
    1.  Define parsers and unparsers and expose them as API elements.
1.  Update the existing tables with the new types

----

| Option 1 | Option 2 | Cons |
| ------- | ---- | ------ |
| &#x2714; | &#x2714; |  Have to spec parser & unparser |
| &#x2714; | ? (createFromArray) | Have to specify copy operator |
| &#x2714; |     | Fixed spec cost in enforce |
|     | &#x2714; | Each attribute significantly increases interface complexity |

I think recurring spec complexity is an issue, but IIUC, that doesn't differentiate option 1 from 2.
Option 1 wins on interface complexity.

**Comment by koto** [comment]
To clarify - there's one important issue with Option 1:

The `el.srcset = x` statement in a browser with native TT support and in a browser with a (non-enforcing) TT-polyfill will behave differently i.e. we lose code portability. This is due to `x` being an array of objects that will not serialize to urlsets that browsers have specced. A custom type lets us define serialization rules internally. This is why I think we need a type that has its string serialization rules defined such that if the enforcement is not enabled `covered.sink = t` behaves the same as `covered.sink = t.toString()` for every sink. In other words, Option 1 is ok, but I think we need a different wrapping type anyway.
 
MVP for Option 2 would be introducing 1 new type for images, and later - a second one for scripts, but still all the types would behave the same (they would wrap over a string). If needed, we can spec the parsers and `createFromArray` functions, but it sounds like it adds complexity for little gain (i.e. authors need to add a separate `createTrustedUrlSet` function if they're using urlsets).

**Comment by mikesamuel** [comment]
@koto Thanks for clarifying.

Can we make that extra type an internal implementation detail?

Maybe this goes back to your "That last part is a bigger change, and should probably require speccing in HTML" to map a JavaScript objects to something with an unparsing stringifier.

**Comment by koto** [comment]
I'm still not sure I understand. I think the type needs to be exposed to JS. In specific, `srcset` setter should not be called with an array, as that will not be portable (and not be backwards-compatible). IOW, this program should have no functional changes in older browsers:

```
if(typeof TrustedTypes == "undefined")TrustedTypes={createPolicy:(n, rules) => rules};

const fooPolicy =TrustedTypes.createPolicy('foo', {
  createSet: (stringS) => process(stringS)
}, false);

img.srcset = fooPolicy.createSet('foo.jpg 320w, bar.jpg 480w');
```

If there is a solution that can keep the tinyfill small, and allows for a better interface, we can try that (some things look promising, e.g. ['foo.jpg 320w', 'bar.jpg 480w'] serializes to the original value). But in general, Option 2 has two important properties: 
 - code portability (even with tinyfill)
 - DOM sinks only get changes that are explainable in IDL. There's a single algorithm, parametrized by the expected type.

**Comment by mikesamuel** [comment]
@koto Are we likely to see an implementation of `createSet: (stringS) =>` that is neither the identity function and that doesn't unparse?

----

> If there is a solution that can keep the tinyfill small, and allows for a better interface, we can try that (some things look promising, e.g. ['foo.jpg 320w', 'bar.jpg 480w'] serializes to the original value)

```js
// Define unparser
function unparse(elements) {
  return elements.map(a => a.map(b => b.replace(/[\t\n\f\r ,]+/g, encodeURIComponent))
      .join(' ')).join(' , ');
}

// Install
const imgProto = HTMLImageElement.prototype;
const descriptor = Object.getOwnPropertyDescriptor(imgProto, 'srcset');
const newDescriptor = Object.assign({}, descriptor);
newDescriptor.set = function (x) {
  return Reflect.apply(
      descriptor.set, this, [ Array.isArray(x) ? unparse(x) : x ]);
};

delete imgProto.srcset;
Object.defineProperty(imgProto, 'srcset', newDescriptor);

// Use polyfilled srcset property
const img = document.createElement('img');
console.group('string');
try {
  img.srcset = '/foo.gif 1x , /bar.gif';
  console.log(`get ${ img.srcset }`);
} finally {
  console.groupEnd();
}

console.group('array');
try {
  img.srcset = [ [ '/baz baz.gif', '1x' ] , [ '/boo.gif' ] ];
  console.log(`get ${ img.srcset }`);
} finally {
  console.groupEnd();
}
```

**Comment by koto** [comment]
I'm not sure I follow - the sink assignment:
```js
  img.srcset = [ [ '/baz baz.gif', '1x' ] , [ '/boo.gif' ] ];
```
would cause functional change if TT were not available (or were available only as a polyfill). In other words, the only sink behavior change should be in a default policy invocation, but the value passed to that policy should have the same form as if TT did not exist (i.e. it should be a string). That's a crucial property we should not break. 

We can introduce additional builders (e.g. builders from an array), policies allow us to do that. However these extra builders should not be called from sink setters, as than we'd be breaking the aforementioned property. Sinks should call the string-accepting function from a default policy, as that is the contract in HTML. 

One extra thing: [\<link imagesrcset\>](https://html.spec.whatwg.org/#attr-link-imagesrcset) is also a srcset attribute.

**Comment by koto** [comment]
We decided to stop requiring TrustedURLs for non-document URL sinks (rule of thumb: if `javascript:` wouldn't work, TrustedURL is not required). This obsoletes this bug (at least, until `script.srcset` comes around).
