### ISSUE TITLE
Consider adding a link and examples to the built in sanitizers ?

### ISSUE THREAD

**Issue by lifaon74** [WICG/trusted-types#148]
As I understand, right now the TrustedTypes doesn't implement any built-in sanitizer. It's just a policy factory API, and the developpers must use their own sanitizer.

After deeply searching into your git, I finally found the [purification](https://wicg.github.io/purification/) draft. Sadly, there is no link and examples on the [TrustedTypes  specs](https://wicg.github.io/trusted-types/dist/spec/#enumdef-supportedtype) about the purification specs, and vice-versa.

It could be worth putting some examples (even if purification is still in draft, you may add some "warn" block). Currently it's pretty hard to do the link between them without exploring deeply the git.

**Comment by mikesamuel** [comment]
Good point.  We are planning on providing tools support as separate libraries and probably help publicize tools that integrate well.

Things like

* sanitizers whose policy code does not include footguns like the one you linked and DOMPurify
* contextually autoescaped template languages that produce and consume trusted types

Out of interest, where did you look while researching this?
If there are stackoverflow tags that we should monitor, I'd love to know.

**Comment by lifaon74** [comment]
I follow the w3c and wicg github and was interested into the TrustedTypes. When reading the doc, I saw that sanitizers where missing and was surpised not to find any link on some sanitizers. So I searched (that was hard and hidden) into the wicg repos until I found the 'purification' repo.

That's why I openend this issue, as it could help other developpers.

**Comment by koto** [comment]
The Trusted Types API is, as you noticed, scoped to being a factory of types (+type enforcement at sinks). We intentionally don't include the sanitizers. That said, an informative note in the spec doesn't hurt, but I'd rather put something that is actionable for the authors, and it seems the work on the purification spec has paused.

@mozfreddyb, is there any work being don on the native purification API?
