### ISSUE TITLE
setTimeout sink needs to allow Function

### ISSUE THREAD

**Issue by mikesamuel** [WICG/trusted-types#159]
[3.2.2. Get Trusted Type compliant string](https://wicg.github.io/trusted-types/dist/spec/#get-trusted-type-compliant-string-algorithm)

> ISSUE 22 input could also be a Function, e.g. for setTimeout. Maybe add or Function to ScriptString and rename to avoid confusion.

This could probably be addressed in [4.1.8. Enforcement in timer functions](https://wicg.github.io/trusted-types/dist/spec/#enforcement-in-timer-functions)
which should link to https://www.w3.org/TR/html5/webappapis.html#timer-initialization-steps
and should run at step 5.2 not 7

> 5. Let task be a task that runs the following substeps:
>     1. ...
>     2. Run the appropriate set of steps from the following list:
>         * If the first method argument is a Function
>             * ...
>         * Otherwise
>             * Perform HostEnsureCanCompileStrings(callerRealm, calleeRealm). If this throws an exception, report the exception.

**Comment by koto** [comment]
As far as I can tell, this is already addressed in the first step of https://wicg.github.io/trusted-types/dist/spec/#enforcement-in-timer-functions.
