### ISSUE TITLE
Non-normative note on 2 argument form of document.open.

### ISSUE THREAD

**Issue by mikesamuel** [WICG/trusted-types#160]
Do we need to guard the two argument form of `document.open`?

Per [mozdev](https://developer.mozilla.org/en-US/docs/Web/API/Document/open#Two-argument_document.open()) probably not

> ## Two-argument document.open()
> This form is now obsolete; it won't throw an error, but instead just forwards to document.open() (i.e. is the equivalent of just running it with no arguments).

Chrome's WebIDL for `document.open` says
```webidl
    [CallWith=Isolate, CEReactions, CustomElementCallbacks, RaisesException, MeasureAs=DocumentOpenTwoArgs]
    Document open(optional DOMString type = "text/html", optional DOMString replace = "");
    [CallWith=Isolate, RaisesException, MeasureAs=DocumentOpenThreeArgs]
    Window open(URLString url, DOMString name, DOMString features);
```

Trusted types guards one definition of `document.open` in [extensions to the document interface](https://wicg.github.io/trusted-types/dist/spec/#extensions-to-the-document-interface).

**Comment by koto** [comment]
How does it behave? Is the replace parameters respected currently in, say,
Moz and Chrome? I can check on browserstack.

**Comment by mikesamuel** [comment]
The replace parameter is just a keyword, so none of the parameters correspond to trusted types.

Definition at 
https://html.spec.whatwg.org/multipage/dom.html#the-document-object:dom-document-open-window

**Comment by koto** [comment]
This seems to be solved: https://wicg.github.io/trusted-types/dist/spec/#extensions-to-the-document-interface
