### ISSUE TITLE
Rename the factory as available on window to window.trustedTypes.

### ISSUE THREAD

**Issue by koto** [WICG/trusted-types#177]
The spec trend is now to start with lowercase, so `window.trustedTypes` instead of `window.TrustedTypes`. 

We should perform the rename as the last step after building + speccing all existing features, such that `window.trustedTypes` has stable features, unlike the current API that is under active development. 

Note to authors: Please feature check before using the API i.e. check that `window.TrustedTypes.createPolicy` exists before calling it.

**Comment by mikesamuel** [comment]
Re the polyfill, I wonder whether making it [es-shim API](https://www.npmjs.com/package/@es-shims/api#api-contract) compatible would ease some of these migration issues.

**Comment by koto** [comment]
Chrome implementation tracked in https://bugs.chromium.org/p/chromium/issues/detail?id=991944.
