### ISSUE TITLE
Make default policy available to tools

### ISSUE THREAD

**Issue by mikesamuel** [WICG/trusted-types#185]
Tools like a template language might want to apply a policy to string inputs, akin to applying the default policy, for example to vet strings that reach `<a href={{x}}>`.  They might benefit from being able to default to the document's default policy.

Maybe expose an `[Unforgeable]` property `TrustedTypes.defaultPolicy` with type `null | TrustedTypesPolicy`.

**Comment by koto** [comment]
That sounds useful, can you add it to the spec?
