### ISSUE TITLE
Integration idea - use Symbol.hasInstance

### ISSUE THREAD

**Issue by koto** [WICG/trusted-types#22]
Libraries could use `Symbol.hasInstance` to refer to some of the internally used custom types as trusted types. That way a custom type could pass an `instanceof` check. It is a double-edged sword though.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/hasInstance

**Comment by mikesamuel** [comment]
Is the intent to have a way to bridge [goog.html.SafeHtml](https://google.github.io/closure-library/api/goog.html.SafeHtml.html) to TrustedHtml, etc.?

**Comment by koto** [comment]
This is deprecated, the new policy-centric design does not seem to require this.
