### ISSUE TITLE
Suggestion: URLs have more than one escaping context

### ISSUE THREAD

**Issue by granthusbands** [WICG/trusted-types#3]
You can't really have just one 'escape'. A parameter name, a path component, a parameter and a hostname all have different escaping rules.

**Comment by koto** [comment]
There is no escaping for the URL context in the proposal. There is *sanitization* instead, which accepts a URL string, makes it absolute (with respect to current `document` base URL), and then makes sure the protocol is `http(s)` - this is to prevent JS execution when assigned to e.g. `a href`.

This would likely be expanded, as we need to represent trusted URLs pointing to executable code differently (Google's equivalent is usually called [trusted resource URL](https://github.com/google/closure-library/blob/master/closure/goog/html/trustedresourceurl.js)), but nevertheless, we don't attempt yet to *escape* different URL components.
