### ISSUE TITLE
Is it possible to lock things down to string constants?

### ISSUE THREAD

**Issue by mikewest** [WICG/trusted-types#4]
It would be lovely if we could have a `CreateFromConstant` method that would allow 

```
Whatever.createFromConstant("https://example.com/")
```

but deny

```
var notAConstant("https://example.com/");
Whatever.createFromConstant(notAConstant);
```

**Comment by mikesamuel** [comment]
How can this be done without static analysis?

We've done reasonably reliable checks in other languages by defining an isProbablyInConstantPool predicate, but I don't know of one for JavaScript and we'd need one that's scoped to origin, realm, or narrower.

**Comment by mikesamuel** [comment]
Since Mike didn't mention this explicitly: https://github.com/mikewest/tc39-proposal-literals

**Comment by koto** [comment]
Shelving this approach for now. It's proven quite difficult to change the language.
