### ISSUE TITLE
bool exposed - argument to createPolicy or member of TrustedTypesInnerPolicy?

### ISSUE THREAD

**Issue by orsi-batiz** [WICG/trusted-types#79]
In the JS code:
  
/*
   * Creates a TT policy.
   *
   * Returns a frozen object representing a policy - a collection of functions
   * that may create TT objects based on the user-provided rules specified
   * in the policy object.
   *
   * @param  {string} name A unique name of the policy.
   * @param  {TrustedTypesInnerPolicy} policy Policy rules object.
   * @param  {boolean=} expose Iff true, the policy will be exposed (available
   *   globally).
   * @return {TrustedTypesPolicy} The policy that may create TT objects
   *   according to the policy rules.
   * @todo Figure out if the return value (and the policy) can be typed.
   */
  function createPolicy(name, policy, expose = false) {
    const pName = '' + name; // Assert it's a string

    if (enforceNameWhitelist && allowedNames.indexOf(pName) === -1) {
      throw new Error('Policy ' + pName + ' disallowed.');
    }

    if (policyNames.indexOf(pName) !== -1) {
      throw new Error('Policy ' + pName + ' exists.');
    }
    // Register the name early so that if policy getters unwisely calls
    // across protection domains to code that reenters this function,
    // policy author still has rights to the name.
    policyNames.push(pName);

    // Only copy own properties of names present in createTypeMapping.
    const innerPolicy = create(null);
    for (const key of getOwnPropertyNames(policy)) {
      if (createFunctionAllowed.call(createTypeMapping, key)) {
        innerPolicy[key] = policy[key];
      }
    }

We have @param expose and @param TrustedTypesInnerPolicy, but we could make expose a member of TrustedTypesInnerPolicy and not need a separate param for it. Any thoughts?

**Comment by koto** [comment]
That was the previous behavior - expose was a key of the policy
object. We decided to move it out to a separate createPolicy parameter
to be able to identify exposed policies more easily, and to a large
extent statically. I'd prefer if this stayed separate for now, unless
more parameters will become necessary.

On 8/30/18, Orsolya Bernadett Batiz <notifications@github.com> wrote:
> In the JS code:
>
> /*
>    * Creates a TT policy.
>    *
>    * Returns a frozen object representing a policy - a collection of
> functions
>    * that may create TT objects based on the user-provided rules specified
>    * in the policy object.
>    *
>    * @param  {string} name A unique name of the policy.
>    * @param  {TrustedTypesInnerPolicy} policy Policy rules object.
>    * @param  {boolean=} expose Iff true, the policy will be exposed
> (available
>    *   globally).
>    * @return {TrustedTypesPolicy} The policy that may create TT objects
>    *   according to the policy rules.
>    * @todo Figure out if the return value (and the policy) can be typed.
>    */
>   function createPolicy(name, policy, expose = false) {
>     const pName = '' + name; // Assert it's a string
>
>     if (enforceNameWhitelist && allowedNames.indexOf(pName) === -1) {
>       throw new Error('Policy ' + pName + ' disallowed.');
>     }
>
>     if (policyNames.indexOf(pName) !== -1) {
>       throw new Error('Policy ' + pName + ' exists.');
>     }
>     // Register the name early so that if policy getters unwisely calls
>     // across protection domains to code that reenters this function,
>     // policy author still has rights to the name.
>     policyNames.push(pName);
>
>     // Only copy own properties of names present in createTypeMapping.
>     const innerPolicy = create(null);
>     for (const key of getOwnPropertyNames(policy)) {
>       if (createFunctionAllowed.call(createTypeMapping, key)) {
>         innerPolicy[key] = policy[key];
>       }
>     }
>
> We have @param expose and @param TrustedTypesInnerPolicy, but we could make
> expose a member of TrustedTypesInnerPolicy and not need a separate param for
> it. Any thoughts?
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/WICG/trusted-types/issues/79


-- 
Best regards,
Krzysztof Kotowicz

**Comment by mikewest** [comment]
To me, the call is significantly clearer if we move everything into the options dictionary. That is:

```
factory.createPolicy({
  "name": "String",
  "createHTML": s => s,
  "exposed": true
});
```

seems significantly more legible at the callsite (or options construction site) than:

```
factory.createPolicy("String", {
  "createHTML": s => s,
}, true);
```

I don't like passing random booleans and strings around when we have a dictionary with named keys sitting right next to them.

**Comment by koto** [comment]
Closing, it seems both implementation are using expose as a separate function argument now.
