### ISSUE TITLE
Browser extensions vs Trusted Types

### ISSUE THREAD

**Issue by koto** [WICG/trusted-types#94]
There's a couple of interesting questions regarding browser extensions and TT. 

1. Should browser extensions be able to create TT policies in their content scripts? If so, should they share the policy namespace (i.e. can the extension content script race to create a policy with an allowed name with the website), or have a separate one?

2. If they are able to create policies, should they be affected by the policy names restrictions, or can they create one at will?

3. Do extensions need to create TT policies, and then TT objects to interact with the DOM XSS sinks, or should they be exempt from the TT enforcement? To respect [prior bevavior](https://www.w3.org/TR/CSP3/#extensions), they should be exempt.

**Comment by koto** [comment]
This is clarified in https://wicg.github.io/trusted-types/dist/spec/#implementation-considerations

**Comment by NicBright** [comment]
I just stumbled upon a violation report (from the application I'm working on) that complains about `"sourceFile": "chrome-extensions"` like this:

```
{
  "age": 9,
  "body": {
    "blockedURL": "trusted-types-sink",
    "columnNumber": 80573,
    "disposition": "report",
    "documentURL": "(...)",
    "effectiveDirective": "require-trusted-types-for",
    "lineNumber": 1,
    "originalPolicy": "(...) trusted-types angular angular#bundler angular#unsafe-bypass angular-extensions#elements default gravity-internal gravity-jquery dompurify gravity 'allow-duplicates';",
    "referrer": "(...)",
    "sample": "Element innerHTML|<select></select>",
    "sourceFile": "chrome-extension",
    "statusCode": 200
  },
  "type": "csp-violation",
  "url": "(...)",
  "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36 (...) altpriv cvcv=2 cexpw=1 smf=0"
}
```

According to this issue and to chapter "7.1. Vendor-specific Extensions and Addons" of the current Editor's Draft (21 November 2024) extensions should be exempt from TT checks.

To me, it looks as if Google's Chrome browser is ignoring this chapter. I've found a blog post that makes it look the same: extensions should be able to conform to trusted types:
https://developer.chrome.com/blog/trusted-types-on-youtube

@koto, what do you think? Should chapter 7.1 be dismissed or is it more of an issue of convincing browser vendors to conform to it?
